import 'dart:convert';
import 'dart:typed_data';
import 'package:flutter/services.dart';

/// Byte-Pair-Encoding tokenizer ported to match the `tokenizers` library
/// configuration used by the Gemma 3 model (see assets/tokenizer/*.bin).
///
/// Pipeline (matches the reference tokenizer.json):
///   1. Normalize: replace ' ' with U+2581 (▁)
///   2. Pre-tokenize: Split on ' ' with MergedWithPrevious behavior
///   3. Split words on added/special tokens (longest match)
///   4. Apply BPE merges (byte_fallback for chars not in vocab)
class GemmaBpeTokenizer {
  GemmaBpeTokenizer._(
    this._vocab,
    this._merges,
    this._addedTokens,
    this._idToToken,
  );

  final Map<String, int> _vocab; // token -> id
  final Map<String, int> _merges; // "left right" -> rank (lower = higher priority)
  final List<_AddedToken> _addedTokens; // sorted by content length desc
  final List<String> _idToToken; // id -> token (for decoding)

  static const _unkId = 3;

  /// Loads the tokenizer from the compact binary assets generated by
  /// scripts/preprocess_tokenizer.py.
  static Future<GemmaBpeTokenizer> load() async {
    final vb = await rootBundle.load('assets/tokenizer/vocab.bin');
    final mb = await rootBundle.load('assets/tokenizer/merges.bin');
    return fromBinaries(
      vb.buffer.asUint8List(vb.offsetInBytes, vb.lengthInBytes),
      mb.buffer.asUint8List(mb.offsetInBytes, mb.lengthInBytes),
    );
  }

  static GemmaBpeTokenizer fromBinaries(Uint8List vocabBin, Uint8List mergesBin) {
    final vocab = <String, int>{};
    final idToToken = <String>[];
    var r = _Reader(vocabBin);
    final vocabCount = r.u32();
    for (var i = 0; i < vocabCount; i++) {
      final token = r.str();
      final id = r.i32();
      vocab[token] = id;
      while (idToToken.length <= id) {
        idToToken.add('');
      }
      idToToken[id] = token;
    }

    final merges = <String, int>{};
    r = _Reader(mergesBin);
    final mergesCount = r.u32();
    for (var i = 0; i < mergesCount; i++) {
      final left = r.str();
      final right = r.str();
      final rank = r.u32();
      merges['$left $right'] = rank;
    }

    final addedTokens = <_AddedToken>[];
    // Special tokens that must be matched verbatim inside input text.
    const specials = {
      '<pad>', '<eos>', '<bos>', '<unk>',
      '<start_of_turn>', '<end_of_turn>', '<image_soft_token>',
      '<start_of_image>', '<end_of_image>', '<mask>', '<BLANK>',
    };
    for (final name in specials) {
      final id = vocab[name];
      if (id != null) addedTokens.add(_AddedToken(name, id));
    }
    addedTokens.sort((a, b) => b.content.length.compareTo(a.content.length));

    return GemmaBpeTokenizer._(vocab, merges, addedTokens, idToToken);
  }

  /// Encodes [text] to token ids (no special tokens prepended).
  List<int> encode(String text) {
    // Step 1: normalizer (Replace ' ' -> U+2581)
    final normalized = text.replaceAll(' ', '\u2581');

    // Step 2: pre-tokenize (Split on ' ' with MergedWithPrevious)
    final words = _splitMergedWithPrevious(normalized);

    final ids = <int>[];
    for (final word in words) {
      _encodeWord(word, ids);
    }
    return ids;
  }

  /// Decodes [ids] back to a string (▁ -> space, byte fallback handled).
  String decode(List<int> ids) {
    final sb = StringBuffer();
    final byteBuf = <int>[];
    final byteRe = RegExp(r'^<0x([0-9a-f]{2})>$');
    void flushBytes() {
      if (byteBuf.isNotEmpty) {
        sb.write(utf8.decode(byteBuf, allowMalformed: true));
        byteBuf.clear();
      }
    }

    for (final id in ids) {
      final token = id >= 0 && id < _idToToken.length ? _idToToken[id] : null;
      if (token == null || token.isEmpty) continue;
      final m = byteRe.firstMatch(token);
      if (m != null) {
        byteBuf.add(int.parse(m.group(1)!, radix: 16));
      } else {
        flushBytes();
        sb.write(token.replaceAll('\u2581', ' '));
      }
    }
    flushBytes();
    return sb.toString();
  }

  List<String> _splitMergedWithPrevious(String s) {    final words = <String>[];
    final buf = StringBuffer();
    for (var i = 0; i < s.length; i++) {
      final ch = s[i];
      if (ch == ' ') {
        // a space merges with the previous piece
        words.add('${buf.toString()}$ch');
        buf.clear();
      } else {
        buf.write(ch);
      }
    }
    if (buf.isNotEmpty) words.add(buf.toString());
    return words;
  }

  void _encodeWord(String word, List<int> out) {
    // Step 3: split the word into segments at added-token occurrences
    // (longest match at each position).
    final segments = <_Seg>[];
    var i = 0;
    while (i < word.length) {
      _AddedToken? match;
      for (final at in _addedTokens) {
        if (at.content.isNotEmpty && word.startsWith(at.content, i)) {
          match = at;
          break;
        }
      }
      if (match != null) {
        segments.add(_Seg(true, match.content));
        i += match.content.length;
      } else {
        final last = segments.isEmpty ? null : segments.last;
        if (last != null && !last.isSpecial) {
          last.text = last.text + word[i];
        } else {
          segments.add(_Seg(false, word[i]));
        }
        i++;
      }
    }

    for (final seg in segments) {
      if (seg.isSpecial) {
        final id = _vocab[seg.text];
        if (id != null) out.add(id);
      } else {
        _applyBpe(seg.text, out);
      }
    }
  }

  void _applyBpe(String word, List<int> out) {
    if (word.isEmpty) return;

    // Build initial units, applying byte fallback for chars not in vocab.
    final units = <String>[];
    for (final rune in word.runes) {
      final ch = String.fromCharCode(rune);
      if (_vocab.containsKey(ch)) {
        units.add(ch);
      } else {
        for (final byte in utf8Encode(ch)) {
          units.add(byteToken(byte));
        }
      }
    }
    if (units.isEmpty) return;

    while (units.length > 1) {
      // find the lowest-rank adjacent pair
      String? bestPair;
      var bestRank = 1 << 62;
      for (var i = 0; i < units.length - 1; i++) {
        final pair = '${units[i]} ${units[i + 1]}';
        final rank = _merges[pair];
        if (rank != null && rank < bestRank) {
          bestRank = rank;
          bestPair = pair;
        }
      }
      if (bestPair == null) break;

      final splitAt = bestPair.indexOf(' ');
      final first = bestPair.substring(0, splitAt);
      final second = bestPair.substring(splitAt + 1);
      final merged = first + second;

      final next = <String>[];
      var i = 0;
      while (i < units.length) {
        if (i < units.length - 1 && units[i] == first && units[i + 1] == second) {
          next.add(merged);
          i += 2;
        } else {
          next.add(units[i]);
          i++;
        }
      }
      units
        ..clear()
        ..addAll(next);
    }

    for (final unit in units) {
      out.add(_vocab[unit] ?? _unkId);
    }
  }

  /// 'a' -> '<0x61>'
  static String byteToken(int byte) {
    final hex = byte.toRadixString(16).padLeft(2, '0');
    return '<0x$hex>';
  }
}

List<int> utf8Encode(String s) {
  final bytes = <int>[];
  for (final rune in s.runes) {
    if (rune < 0x80) {
      bytes.add(rune);
    } else if (rune < 0x800) {
      bytes.add(0xC0 | (rune >> 6));
      bytes.add(0x80 | (rune & 0x3F));
    } else if (rune < 0x10000) {
      bytes.add(0xE0 | (rune >> 12));
      bytes.add(0x80 | ((rune >> 6) & 0x3F));
      bytes.add(0x80 | (rune & 0x3F));
    } else {
      bytes.add(0xF0 | (rune >> 18));
      bytes.add(0x80 | ((rune >> 12) & 0x3F));
      bytes.add(0x80 | ((rune >> 6) & 0x3F));
      bytes.add(0x80 | (rune & 0x3F));
    }
  }
  return bytes;
}

class _Reader {
  _Reader(this._bytes);
  final Uint8List _bytes;
  int _pos = 0;

  int u32() {
    final v = ByteData.sublistView(_bytes, _pos, _pos + 4).getUint32(0, Endian.little);
    _pos += 4;
    return v;
  }

  int i32() {
    final v = ByteData.sublistView(_bytes, _pos, _pos + 4).getInt32(0, Endian.little);
    _pos += 4;
    return v;
  }

  String str() {
    final len = u32();
    final bytes = _bytes.sublist(_pos, _pos + len);
    _pos += len;
    return utf8.decode(bytes);
  }
}

class _Seg {
  _Seg(this.isSpecial, this.text);
  final bool isSpecial;
  String text;
}

class _AddedToken {
  _AddedToken(this.content, this.id);
  final String content;
  final int id;
}
